# Generated by Django 4.2.20 on 2025-04-17 11:54

import analysis_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BilliardAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=analysis_app.models.image_upload_path,
                        verbose_name="台球图片",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "json_result",
                    models.JSONField(blank=True, null=True, verbose_name="分析JSON"),
                ),
                (
                    "text_result",
                    models.TextField(blank=True, null=True, verbose_name="分析结论"),
                ),
            ],
            options={
                "verbose_name": "台球分析",
                "verbose_name_plural": "台球分析",
                "ordering": ["-created_at"],
            },
        ),
    ]
