# Generated by Django 4.2.20 on 2025-04-22 15:22

import analysis_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0002_billiardanalysis_detected_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billiardanalysis",
            name="detected_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=analysis_app.models.detected_image_path,
                verbose_name="检测结果图片",
            ),
        ),
    ]
